# Generated by Django 3.2.6 on 2021-08-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='avaliacao',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
