# Generated by Django 3.2.6 on 2021-08-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_produto',
            field=models.ImageField(default='didi.jpg', upload_to=None),
        ),
    ]
